version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./DotaDashboard-BE/Dockerfile
    ports:
      - "5056:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./DotaDashboard-FE/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
